name: Cupos - check (5 min)

on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci
      - run: npx playwright install chromium

      - uses: actions/cache@v4
        with:
          path: state.json
          key: state-cache-v1

      - name: Run
        env:
          MODE: check
          TG_TOKEN: ${{ secrets.TG_TOKEN }}
          TG_CHAT_ID: ${{ secrets.TG_CHAT_ID }}
          MONTHS_TO_CHECK: ${{ secrets.MONTHS_TO_CHECK }}
        run: node run.js

      - uses: actions/cache@v4
        with:
          path: state.json
          key: state-cache-v1
